### ISSUE TITLE
Add possibility to use different version of InfluxDB

### ISSUE THREAD

**Issue by fsanaulla** [APISENSE/embed-influxDB#15]

**Comment by fsanaulla** [comment]
Assignee it to me.

**Comment by aveuiller** [comment]
Hello,
I added the last production version to available versions (see this PR: https://github.com/APISENSE/embed-influxDB/pull/17).

I don't know if that will solve your need? If not, always feel free to contribute on an open source software ;)

**Comment by fsanaulla** [comment]
@aveuiller It's totally fine. Thank you.
