### ISSUE TITLE
Embedded Influx doesn't work on mac os

### ISSUE THREAD

**Issue by VladimirApolaiko** [APISENSE/embed-influxDB#16]
I use the provided code snippet to start embedded influx on mac os 10.12.6, but I every time I try to run  it I get the following message: [influxd error]/var/folders/z6/zxktn8v10nx_ssb1zctm_5w80000gn/T/extract-c9d95ee0-f9fb-4387-bb94-e85806f45c21influxd: /var/folders/z6/zxktn8v10nx_ssb1zctm_5w80000gn/T/extract-c9d95ee0-f9fb-4387-bb94-e85806f45c21influxd: cannot execute binary file
[influxd error]

**Comment by novaesis** [comment]
@rouvoy I am running into this issue as well. Is there a timeframe of when this is going to be fixed? It works great on linux environment but on MacOS I get "cannot execute binary file". Is it because there is not a direct distribution of InfluxDB for MacOS?

**Comment by melodious** [comment]
+1 We could really use this!

**Comment by rouvoy** [comment]
Unfortunately, we do not have the necessary resources to address this issue currently. But, if one of you can dig into it, we will be happy to accept a pull request.

**Comment by fsanaulla** [comment]
You can try [this](https://github.com/testcontainers/testcontainers-java) as the temporary solution. It already has an InfluxDB module.

**Comment by aveuiller** [comment]
Hello,

Unfortunately you're right @nkglenn, there is no binary package for MacOS. 

As you can see on the [download page](https://portal.influxdata.com/downloads), installation for MacOS is redirected to HomeBrew, which will manually download the github project and build it using `go install`.

It may be possible to integrate this kind of behavior but I fear that this is currently not well supported by the underlying library (i.e. https://github.com/flapdoodle-oss/de.flapdoodle.embed.process).

**Comment by aveuiller** [comment]
The compatibility with MacOS is now available in version 1.2.0.
