### ISSUE TITLE
Expose server state

### ISSUE THREAD

**Issue by fsanaulla** [APISENSE/embed-influxDB#19]
It's will be great to have the opportunity to be able to check server state, for some internal manipulation, like to lock the thread until influx not stopped and cleaned properly.
 Will be enough to have some getter method that will safely expose server state.

```
public ServerState getState() {
   return currentState;
}
```

**Comment by fsanaulla** [comment]
Also, multiple tests executed sequentially fail time2time, with unavailable to clean/stop resources used previously. Addition information can be found here: https://travis-ci.org/fsanaulla/scala-embedinflux/builds/563001457.

Sometimes it works, sometimes - no.

Thank you!

**Comment by aveuiller** [comment]
Hello, 

Thanks for using this project. :)

Adding a getter on the State is a good idea! Would you mind doing a pull request with the changes?

As for the bug I will try to have a look at it. However, it does sound like a race condition. Maybe the improvement you stated earlier to wait for the process to start / be closed could be of use?

Do you have more details on the specificities of your execution? Namely if the execution was in parallel and the number of parallel nodes you started if applicable.

**Comment by aveuiller** [comment]
Hello,

I know it's been a while, but the `ServerState` information is now available on v1.3.1. :)
