### ISSUE TITLE
Refactor configuration process

### ISSUE THREAD

**Issue by aveuiller** [APISENSE/embed-influxDB#6]
I think that overall, the configuration system I created initially has to be rethought in order to expose a more modular interface to create configuration sections.

This would enable us in the long run to add [more configuration possibilities](https://docs.influxdata.com/influxdb/v1.4/administration/config#udp-settings-udp) about udp, among others.

**Comment by fsanaulla** [comment]
It actually includes #5.
What you think about applying [builder](https://en.wikipedia.org/wiki/Builder_pattern#Java) pattern in config generation?
As a bonus option, it can feed path to already existing config.
I can help you with it.

**Comment by aveuiller** [comment]
The Builder pattern is indeed a good idea, I created a pull request, implementing it if you want to have a look. :)

Your idea of feeding an existing config file is interesting too and I think it should deserve an issue of its own.
