### ISSUE TITLE
Enable the user to feed an existing configuration file

### ISSUE THREAD

**Issue by aveuiller** [APISENSE/embed-influxDB#8]
As mentioned by @fsanaulla  in #6, we should propose a `ConfigurationWriter` implementation able to use an existing influx config file.

I think in this case the methods should have the following behaviour:
- `addStatement`: Throw an `UnsupportedOperationException`.
- `writeFile`: Return the user given config file.
- `getDataPath`: The main difficulty here since we should parse the given configuration file to retrieve the data path. And even if our configuration centralize all the data in a directory, the user defined configuration may come with multiple data directory.

Maybe we should give the option to the user to set a data directory to remove on server stop? This would avoid us to parse the given configuration file.

**Comment by fsanaulla** [comment]
@aveuiller what about specifying the path to existing config file, without parsing. See [this](https://docs.influxdata.com/influxdb/v1.5/administration/config/#using-the-configuration-file).

**Comment by aveuiller** [comment]
That's already what we are doing in the end, so yes ultimately we don't have to parse the configuration file.

Having said that, the embedded influx server is made to automatically remove the created data directory on server stop (hence the `getDataPath` function in the interface). 
This leads to 2 possibilities: either we don't care about deletion if the user gives us an already written file, or we ask the user for the directory to remove on server stop.

I don't really like both of the solutions since it duplicate the `dataPath` information, already present in the configuration file. But I think we can let the user choose if he wants some file deleted at the end of the tests, for instance by providing two constructors.

What do you think about it?

**Comment by fsanaulla** [comment]
@aveuiller I think to let a user choose when to delete data, it's a nice option.
